### ISSUE TITLE
Dynamic routing and data longform structure

### ISSUE THREAD

**Issue by joakimkm** [TryGhost/Ghost#10054]
**Issue Summary**

Data property in routes.yaml do not work correctly.
I would like data to be fetched and than use it in my handlebars template as {{customData}}.
To accomplish this I use the longform structure [documentation](https://docs.ghost.org/concepts/routing)

**To Reproduce:**

My routes.yaml file:

```
routes:

collections:
  /crossword/:
    permalink: /crossword/{slug}/
    template:
      - tag-crossword
    data:
     customData:
      resource: posts
      filter: tags:crossword
      type: read
  /:
    permalink: /{slug}/
    template:
      - index

taxonomies:
  tag: /{slug}/
  author: /author/{slug}/
```

Template for /crossword/ is loaded correctly but {{customData}} is undefined in template.
The data does not exist either in handlebars options.data object. 
I have tried to remove filter from data property, but it still not working.
I have followed the documentation and do not see what may be wrong.
