### ISSUE TITLE
Dynamic routing data prop return 404 for all posts

### ISSUE THREAD

**Issue by kolybasov** [TryGhost/Ghost#10228]
Thanks for the Ghost, it is awesome!

### Issue Summary

Sorry if it was already reported, I've tried to search but didn't find the same issue.

I've created theme that uses dynamic routing with featured posts always at the top but featured posts have 404 url's. Main page posts have correct urls.

https://youtu.be/8Qp01ehiins

### To Reproduce

There is a repo with default Ghost setup and changes for routes.yaml and Casper theme https://github.com/kolybasov/ghost-dynamic-routing-data-404-bug. You can use this repo or recreate step by step.

1. Install local ghost
2. Update `routes.yaml`

```yaml
routes:

collections:
  /:
    permalink: /{slug}/
    template:
      - index
    filter: featured:false
    data:
      featured:
        resource: posts
        type: browse
        include: authors,tags
        filter: featured:true
        limit: 3

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

3. Update `Casper/index.hbs`

```hbs
{{!-- The main content area --}}
<main id="site-main" class="site-main outer">
    <div class="inner">
        {{#if featured.posts}}
            <div class="post-feed">
                {{#foreach featured.posts}}
                    {{> "post-card"}}
                {{/foreach}}
            </div>

            <hr><br><hr>
        {{/if}}

        <div class="post-feed">
            {{#foreach posts}}

                {{!-- The tag below includes the markup for each post - partials/post-card.hbs --}}
                {{> "post-card"}}

            {{/foreach}}
        </div>

    </div>
</main>
```

4. Update any post to be featured
5. Open index page and try to open any post at the top

**Actual result**: 404 page
**Expected result**: post page

### Some information that may be useful

There is a check if resource matches the filter https://github.com/TryGhost/Ghost/blob/3017959b2f300f7b14727d428c6788ca3640c628/core/server/services/url/UrlGenerator.js#L97-L118 because we have the filter it executes `this.nql.queryJSON(resource.data)` and this check returns true for the main posts on the page and false for the featured one because it tries to match all posts by query `{'featured': true}`. And because of negative check it do not add all posts to `this.urls`.

### Technical details:

* Ghost Version: 2.6.2
* Node Version: 10.13.0
* Browser/OS: Safari/macOS
* Database: SQLite3
