### ISSUE TITLE
[route] collection filters do not apply correctly on /:

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#10230]
Hello folks!

I'm following [from this conversation in the forum](https://forum.ghost.org/t/collection-filters-works-well-on-the-homepage-but-breaks-under-tags-section/4273/3?u=pascalandy). My goal is to filter out some tags from the Ghost’s homepage.

### EDIT: Little hack

[For now, this works](https://github.com/TryGhost/Ghost/issues/10230#issuecomment-444264911)

### Issue
I’m applying this yaml but no filtering occurs on https://mysite.com/en/
**EDIT**: The result in my case, is that those tags ([how-to, about, under-the-hood]) do still appears in Ghost’s homepage.

To be clear about my domains:
- https://mysite.com/ is served by Caddy (static pages)
- https://mysite.com/en/ is served by Ghost

```
# filters out few tags from Ghost's homepage
routes:
  /:
    controller: channel
    filter: tag:-[how-to,about,under-the-hood]

# redefine the collections as I we can't define /: twice
collections:
  /archive/:
    permalink: /{slug}/
    template:
      - index

# default values
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

### Technical details:

* Ghost Version: 2.1.1
* CLI version: 1.9.4
* Node Version: 10.14.10
* Browser/OS: chrome 66, osx 10.13.4
* Server-side: Alpine:3.8 in Docker [using this image](https://travis-ci.org/firepress-org/ghostfire/branches)
* Database: sqlite
