### ISSUE TITLE
Docker container restart fails after theme was modified

### ISSUE THREAD

**Issue by euri10** [TryGhost/Ghost#10305]
Welcome to Ghost's GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

I have a running docker container where I added a theme (ghostium) that was running fine.
I ended up doing a `docker-compose down` then a `docker-compose up -d --build` and faced this error.
I was able to solve it in a non-trivial way as described below.

the error
```
[2018-12-29 15:56:15] INFO Ghost is running in production... 
[2018-12-29 15:56:15] INFO Your blog is now available on https://blog.bartab.fr/ 
[2018-12-29 15:56:15] INFO Ctrl+C to shut down 
[2018-12-29 15:56:15] INFO Ghost boot 2.15s 
INFO [2018-12-29 15:56:26] "GET /ghost/" 500 9ms
TypeError: Cannot read property 'engine' of undefined
    at ghostLocals (/var/lib/ghost/versions/2.7.1/core/server/web/shared/middlewares/ghost-locals.js:16:53)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:275:10)
    at compression (/var/lib/ghost/versions/2.7.1/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:275:10)
    at emitEvents (/var/lib/ghost/versions/2.7.1/core/server/web/shared/middlewares/emit-events.js:12:5)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/ghost/versions/2.7.1/node_modules/express/lib/router/index.js:284:7
```

### To Reproduce

1. install ghost with mysql with that `docker-compose.yml `and Dockerfile

MYSQL_ROOT_PASSWORD and other env variables are in the same folder in `.env` file

the traefik part can be skipped but you'll need to expose ports in the docker-compose file

docker-compose.yml
```
version: '3.7'
volumes:
  mysql_ghost_volume:
  ghost_volume:
networks:
  web:
    external: true
services:
 mysql:
  image: mysql:5.7
  container_name: mysql
  volumes:
    - mysql_ghost_volume:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
 ghost:
  build: .
  image: ghost:latest
  container_name: ghost
  volumes:
    - ghost_volume:/var/lib/ghost
  restart: always
  environment:
    url: REDACTED
    database__client: mysql
    database__connection__host: mysql
    database__connection__user: ${MYSQL_USER}
    database__connection__password: ${MYSQL_PASSWORD}
    database__connection__database: ${MYSQL_DATABASE}
  labels:
    - "traefik.enable=true"
    - "traefik.backend=ghost"
    - "traefik.frontend.rule=Host:REDACTED"
    - "traefik.port=2368"
    - "traefik.docker.network=web"
  networks:
    - default
    - web
  depends_on:
    - mysql
  entrypoint: ["wait-for-it.sh", "mysql", "--", "docker-entrypoint.sh"]
  command: ["node", "current/index.js"]
```

Dockerfile
```
FROM ghost:latest
RUN apt-get update -y && \
    apt-get install -y mysql-client
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
```

wait-for-it.sh
```
#!/bin/bash
set -e
host="$1"
shift
cmd="$@"
until mysql -hmysql -p"3306" -u"${database__connection__user}" -p"${database__connection__password}" -D"${database__connection__database}" ; do
  >&2 echo "MySQL is unavailable - sleeping"
  sleep 1
done
>&2 echo "MySQL is up - executing command"
exec "$@"
```
2. Add ghostium as the theme and activate it, save
3. Do a `docker-compose down` then a `docker-compose up -d --build` and get the error above.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I would love to restart the container, this seems like the theme isn't found. The way I had to get into a clean stat was:
1. docker exec -it mysql mysql -u MYSQL_USER -p
2. mysql> use MYSQL_DATABASE;
3. mysql> update settings set value='casper' where settings.key='active_theme';

### Technical details:

* Ghost Version: latest of docker
* Node Version: node 8 as per ghost 2 latest image
* Browser/OS: debian buster
* Database: mysql
