### ISSUE TITLE
Update default routes.yaml syntax

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#10456]
The current default `routes.yaml` file looks like this, which is a holdover from pre-2.0 when there were multiple templates being used by default in the main collection.

```yaml
collections:
  /:
    permalink: /{slug}/
    template: 
      - index
```

As this is no longer the case, it can be cleaned up and made simpler using equivalent syntax:

```yaml
collections:
  /:
    permalink: /{slug}/
    template: index
```

There should be no change in behaviour or any knock-on effects from this - it's just a different syntax for the exact same thing.
