### ISSUE TITLE
How to install ghost with mysql and ssl in docker?

### ISSUE THREAD

**Issue by sreerajnova** [TryGhost/Ghost#10517]
I just created a docker file but whenever i run this docker compose file i get error . database is not connecting each other with docker ghost container or its never get install with database. dockerized ghost container getting error with mysql database . here is the docker file i made

```
`version: '3.1'
services:
 ghost:
    image: ghost:latest
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: password
      database__connection__database: ghost
    GHOST_HOST: malayalam.techie.today
    VIRTUAL_HOST: sub.example.com
    LETSENCRYPT_HOST: sub.example.com
    LETSENCRYPT_EMAIL: web@sub.example.com
 db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
networks:
    default:
       external:
         name: webproxy`
```

Any one please help to configure it to correctly ? its keep getting mysql password error but all passwords are correct is this a bug with mariadb or my error ?
