### ISSUE TITLE
`data: post.slug` breaks meta layer on index collection page

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10542]
Steps to reproduce:

```
collections:
  /blog/:
     permalink: /blog/{slug}/
     data: post.known
```

Serve /blog/. See error in stdout

```
MESSAGE: Cannot read property 'name' of null

TypeError: Cannot read property 'name' of null
    at getPostSchema (/ghost/ghost-workspace2/core/server/data/meta/schema.js:82:61)
```

**Comment by gargol** [comment]
@kirrg001 wasn't able to reproduce this one. Used following configuration for collections:
```
collections:
  /blog/:
     permalink: /blog/{slug}/
     data: post.unknown
```
Both http://ghost.local/blog/ and http://ghost.local/blog/cant-find-me returned regular `404` with no additional errors in the output. Maybe there are some additional steps I'm missing?

**Comment by kirrg001** [comment]
Did you try a known post slug?

**Comment by gargol** [comment]
Tried following. Published post renders normally: http://ghost.local/just-a-page/ , and when going to http://ghost.local/blog/just-a-page/ it renders a 404 like above.

**Comment by kirrg001** [comment]
```
collections:
  /blog/:
     permalink: ..
     data: post.known
```

Serve /blog/ reproduces the problem.
