### ISSUE TITLE
Remove featured posts from default collection

### ISSUE THREAD

**Issue by NistorCristian** [TryGhost/Ghost#10587]
Hi,

I found something that is pretty strange while I was playing with routes. I tried to remove all the featured post from `/` and then `get` them and display them above the normal list of post. 

In routes I did:

```
routes:

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: featured:false

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

To remove the featured posts from home. Then I did:

```
{{#get "posts" filter="featured:true" include="tags,authors"}}
    {{#foreach posts}}
        {{> "post-card"}}
    {{/foreach}}
{{/get}}
```

The featured posts are displayed but the links don't work. They are something like this:
`http://localhost:2368/p/some-strange-id`

Even if I try to access directly they don't work. 

This makes sense since I removed featured from `/` but I still want them :)

### Technical details:

* Ghost Version: 2.16.3
