### ISSUE TITLE
Only digits mysql password crashes the server

### ISSUE THREAD

**Issue by knshiro** [TryGhost/Ghost#10634]
### Issue Summary

If the password of the mysql db connection is set in an environment variable and only contains digits the server crashes.

### To Reproduce

1. Copy this in `docker-compose.yml`
```
version: '2'
services:
  ghost:
    image: ghost:2-alpine
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__port: "3306"
      database__connection__user: root
      database__connection__password: "35225951"
    ports:
      - 2368:2368
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "35225951"
```
2. run `docker-compose up db` and wait for the db to be intialized then kill it with `ctrl+c`
3. run `docker-compose up`

Stacktrace:
```
ghost_1  | /var/lib/ghost/versions/2.18.2/node_modules/mysql/lib/protocol/Parser.js:80
ghost_1  |         throw err; // Rethrow non-MySQL errors
ghost_1  |         ^
ghost_1  |
ghost_1  | TypeError: "value" argument must not be a number
ghost_1  |     at Function.Buffer.from (buffer.js:186:11)
ghost_1  |     at Object.Auth.token (/var/lib/ghost/versions/2.18.2/node_modules/mysql/lib/protocol/Auth.js:29:29)
ghost_1  |     at Handshake._sendCredentials (/var/lib/ghost/versions/2.18.2/node_modules/mysql/lib/protocol/sequences/Handshake.js:99:14)
ghost_1  |     at Handshake.HandshakeInitializationPacket (/var/lib/ghost/versions/2.18.2/node_modules/mysql/lib/protocol/sequences/Handshake.js:81:10)
ghost_1  |     at Protocol._parsePacket (/var/lib/ghost/versions/2.18.2/node_modules/mysql/lib/protocol/Protocol.js:278:23)
ghost_1  |     at Parser.write (/var/lib/ghost/versions/2.18.2/node_modules/mysql/lib/protocol/Parser.js:76:12)
ghost_1  |     at Protocol.write (/var/lib/ghost/versions/2.18.2/node_modules/mysql/lib/protocol/Protocol.js:38:16)
ghost_1  |     at Socket.<anonymous> (/var/lib/ghost/versions/2.18.2/node_modules/mysql/lib/Connection.js:91:28)
ghost_1  |     at Socket.<anonymous> (/var/lib/ghost/versions/2.18.2/node_modules/mysql/lib/Connection.js:502:10)
ghost_1  |     at emitOne (events.js:116:13)
ghost_1  |     at Socket.emit (events.js:211:7)
ghost_1  |     at addChunk (_stream_readable.js:263:12)
ghost_1  |     at readableAddChunk (_stream_readable.js:250:11)
ghost_1  |     at Socket.Readable.push (_stream_readable.js:208:10)
ghost_1  |     at TCP.onread (net.js:601:20)
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
I expect the server to run even if the password only has digits. I encountered that while working on deploying on heroku here https://github.com/knshiro/ghost-heroku and the allocated random password only contained digits.

### Technical details:

* Ghost Version: 2
* Node Version: 
* Browser/OS: Linux alpine
* Database: MySQL 5.7
