### ISSUE TITLE
How can i change the domain name in the container?

### ISSUE THREAD

**Issue by kdyzm** [TryGhost/Ghost#10740]
I have completed the build using docker-compose, the docker-compose file is as follows:
``` yml
version: '3.1'

services:

  ghost:
    image: ghost:2.20.1
    restart: always
    ports:
      - 80:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: http://blog.kdyzm.cn
    depends_on:
      - db 
  db: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```
Now i can access by blog.kdyzm.cn , but if my domain name changes, how can I modify it?such as blog.kdyzm.com or https://blog.kdyzm.cn
