### ISSUE TITLE
ECONNRESET with pool setting

### ISSUE THREAD

**Issue by ozeranskiy** [TryGhost/Ghost#10742]
Hello! I use https://hub.docker.com/_/ghost (docker swarm, db mariadb (master->slave), ghost version 2.22-alpine) and my config for connect database:

```
        environment:
          database__client: mysql
          database__connection__host: mariadb-master
          database__connection__user: user
          database__connection__password: password
          database__connection__database: database
          database__pool__min: 2
          database__pool__max: 10
          database__pool__ping: function (conn, cb) { conn.query('SELECT 1', cb); }  }
          admin__url: https://domain/blog/
          url: https://domain/blog/
```

but I get an error after a while:
```
ECONNRESET
```
MariaDB has pool settings:
```
  mariadb-master:
    image: bitnami/mariadb:10.1.40-debian-9-r0
    volumes:
      - mariadb-data-master:/bitnami/mariadb
    networks:
      - internal
    labels:
      - traefik.enable=false
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: user
      MARIADB_PASSWORD:password
      MARIADB_DATABASE: database
      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: repl_user
      MARIADB_REPLICATION_PASSWORD: password
      MARIADB_EXTRA_FLAGS: --thread-handling=pool-of-threads
```
Help me please with problem.
