### ISSUE TITLE
Incorrect sort order in channels with several tags

### ISSUE THREAD

**Issue by konstaner** [TryGhost/Ghost#11076]
I use channel that filter posts by tag:
```
routes:
  /news-events/:
    controller: channel
    filter: tag:[news,events]
    template: channel-news
    order: published_at desc
```

In template _channel-news_ i load posts like this:
```
{{#foreach posts}}
  {{> "post-card"}}
{{/foreach}}
```

It works fine and posts sorting order is correct only if post has one tag assigned. **If post has two ore more tags, than it ignores `order: published_at desc` and displays on the first position.**

Then I tried to get posts like this:
```
            {{#get "posts" order="published_at desc" include="tags"}}
                {{#foreach posts}}
                    {{> "post-card"}}
                {{/foreach}}
            {{/get}}
```
In this variant sort order is ok even if post has several tags. But it **ignores filter from routes.yaml and show all posts.**

Finally, I add filter to #get helper and it solves my problem, but seems that in this variant I don't need channels at all and can use collections.

### Technical details:

* Ghost Version: 2.30.2
* Node Version: official docker container
* Browser/OS: chrome/safari, macos
* Database: sqlite
