### ISSUE TITLE
[features] A health check endpoint

### ISSUE THREAD

**Issue by lzhuor** [TryGhost/Ghost#11181]
Could we please add a simple health api in `index.js`? 

It will serve our needs for load balancers (GCP for us), site reliability monitoring. I am creating a PR for it but seeking for your advice in advance.

**Comment by lzhuor** [comment]
Reopening

**Comment by jakubgs** [comment]
Really? No healthcheck endpoint? Seriously?

**Comment by jakubgs** [comment]
@lzhuor you said "Reopening" but you never reopened it.

**Comment by damusix** [comment]
Having issues with a restarting container on ECS. Root gives me a 302 which is considered unhealthy. Ghost needs a healthcheck endpoint to keep up with modern deployment strategies...

**Comment by kevinansfield** [comment]
If you need a 200 that isn't cached you can hit an API endpoint. `/ghost/api/v3/admin/site/` is unauthenticated.

**Comment by jakubgs** [comment]
```
 % curl -s 'http://localhost:8083/ghost/api/v3/admin/site/' -H 'X-Forwarded-Proto: https' | jq .
{
  "site": {
    "title": "Example",
    "description": "Example Blog",
    "logo": "/content/images/logo.png",
    "url": "https://blog.exampl.org/",
    "version": "3.27"
  }
}
```
Looks good. But how could I have possibly found this in the docs?

There should be a `/health` that shows essentially the same thing and be documented.

**Comment by ethankent** [comment]
Not having a health check route seems to make Ghost impossible to run behind a load balancer if you need https enabled.

**Comment by sneko** [comment]
I totally agree, that's a total mess to make such a simple thing. I see 3 things here:
* A dedicated endpoint should exist (sine the "solution" above will varify depending on the Ghost version)
* Even if HTTPS is used for the public/admin URL, the server should accept HTTP for the `/health` endpoint
* Moreover, for the `/health` endpoint the server should not check the `Host: xxxx` header because it expect the defined URL so when doing it with `localhost:2368/ghost/api/...` the connection is refused.

I'm working on a Kubernetes environment, here is an example how you can set the healthchecks on your blog deployment:
```
        readinessProbe:
          httpGet:
            path: /ghost/api/v4/admin/site/
            port: deployment-port
            httpHeaders:
            - name: X-Forwarded-Proto
              value: https
            - name: Host
              value: blog.mydomain.com
        livenessProbe:
          httpGet:
            path: /ghost/api/v4/admin/site/
            port: deployment-port
            httpHeaders:
            - name: X-Forwarded-Proto
              value: https
            - name: Host
              value: blog.mydomain.com
```

Hope it helps ❤️
