### ISSUE TITLE
Can't custom rss

### ISSUE THREAD

**Issue by hzb** [TryGhost/Ghost#11251]
### Issue Summary

The custom rss doesn't work

### To Reproduce

1. Do as this article asks:  https://ghost.org/tutorials/custom-rss-feed/
2. Visit the custom rss url https://domainname/podcast/rss, and you will get the original rss, not custom rss.

### Technical details:

* Ghost Version: 2.31.0 (development)
* Node Version: 10.16
* Browser/OS: Firefox on macOS catalina
* Database: Sqlite3 

### More details

![df0b5c91bffd890604a43e5aaf1ce4852c670059](https://user-images.githubusercontent.com/535675/67068365-73bdd380-f1ac-11e9-8f7f-c8674e4ac892.png)

Files within my theme, and code in `routes.yaml`

```
routes:

/podcast/rss/:
  template: podcast/rss
  content_type: text/xml

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-podcast
  /podcast/:
    permalink: /podcast/{slug}/
    filter: tag:podcast

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

**Comment by allouis** [comment]
Your `routes.yaml` looks like it's not formatted correctly, can you try like this?
```
routes:
  /podcast/rss/:
    template: podcast/rss
    content_type: text/xml

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-podcast
  /podcast/:
    permalink: /podcast/{slug}/
    filter: tag:podcast

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
