### ISSUE TITLE
Route collections don't filter pages

### ISSUE THREAD

**Issue by sampumon** [TryGhost/Ghost#11353]
### Issue Summary

Per [documentation](https://ghost.org/tutorials/multi-language-content/), "this configuration will allow you to filter your posts and pages that contain multi-language content using tags in the editor."

However, this only works for posts, not for pages.

### To Reproduce

1. routes.yaml
```
collections:
  /en/:
    permalink: /en/{slug}/
    filter: 'tag:en'
  /fi/:
    permalink: /fi/{slug}/
    filter: 'tag:fi'
  /:
    permalink: /{slug}/
    filter: 'tag:-[fi,en]'
```

(simpler two-entry inversed collections, as in documentation, work here too.)

2. Restart Ghost

3. Create
a) page `authors` with tag `en`
b) post `makers` with tag `en`

4. Urls generated:
a) http://localhost:2368/authors/
b) http://localhost:2368/en/makers/

I don't see why this should only work for posts. My main use case is pages: [uneton48.com](https://uneton48.com/en/)

Duplicate: #10728 

### Technical details:

* Ghost Version: 3.0.2
* Node Version: v10.16.1
* Browser/OS: Chrome/macOS
* Database: sqlite3
