### ISSUE TITLE
ghost 2 or 3 can not deployed by docker-compose

### ISSUE THREAD

**Issue by happyxhw** [TryGhost/Ghost#11411]
this is my yml (modified from official yml for ghost 1):
```
version: '3.1'

services:

  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 8081:2368
    environment:
      url: https://xxxx.cn
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: '1234'
      database__connection__database: ghost
    volumes:
      - /home/ubuntu/apps/ghost/data/ghost_content:/var/lib/ghost/content
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - /home/ubuntu/apps/ghost/data/ghost_mysql:/var/lib/mysql
```

this is the error:
![image](https://user-images.githubusercontent.com/44490504/69393453-26d19d80-0d14-11ea-8aa6-8f736f516cc5.png)

it seems ghost can not connect to mysql

ghost 1 is ok

the official docker doc is outdate，please update the doc for 2.0+
