### ISSUE TITLE
Bookmark cards : URL from my own blog not displayed as Bookmark cards

### ISSUE THREAD

**Issue by MichaelCaraccio** [TryGhost/Ghost#11533]
### Issue Summary

Bookmarks card from my own blog are not displayed. It works with others website url.

### To Reproduce

1. Create a new post
2. Paste url (of my own blog)
3. Wait it process
4. Only url is displayed

OR

1. Create a new post
2. + Button -> Bookmark -> paste url
3. Wait it process
4. Tell me to retry or show url

### Technical details:

* Ghost Version: 3.3.0

<img width="721" alt="Screenshot 2020-01-20 at 17 07 43" src="https://user-images.githubusercontent.com/7326386/72713393-eec9c800-3ba7-11ea-8d4f-2a585009934e.png">

I'm using Casper Theme. I changed the routes.yaml :

```yaml
routes:

collections:
  /:
    permalink: /{slug}/
    template:
      - index
    filter: tag:-[photography]
  /photography/:
    permalink: /tag/photography/{slug}/
    template:
      - index
    filter: tag:[photography]
  /programming/:
    permalink: /tag/programming/{slug}/
    template:
      - index
    filter: tag:-[photography]

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
