### ISSUE TITLE
Unable to create a collection of untagged posts

### ISSUE THREAD

**Issue by daviddarnes** [TryGhost/Ghost#11728]
### Issue Summary
Inspired by a [poll on the forum](https://forum.ghost.org/t/please-add-a-none-pseudo-tag/13363): When creating collections in a routes.yaml file it's possible to omit untagged posts from a collection using the filter `filter: primary_tag:-null` like so:
```
collections:
  /:
    permalink: /{slug}/
    template: index
    filter: primary_tag:-null
```
These untagged posts can then match the filter of other collections defined. However for pagination to work correctly the collection listing untagged posts must be able to filter by them like so:
```
  /untagged/:
    permalink: /untagged/{slug}/
    template: index
    filter: primary_tag:null
```
Using `primary_tag:null` as a filter prevents untagged posts from showing in the collection. The post is rendered but the post won't be shown on the collection page.

### To Reproduce

1. Download `routes.yaml` from Ghost admin
2. Modify the collections definition to the following:
    ```
    collections:
      /:
        permalink: /{slug}/
        template: index
        filter: primary_tag:-null
      /untagged/:
        permalink: /untagged/{slug}/
        template: index
        filter: primary_tag:null
    ```
2. Upload the `routes.yaml` to Ghost admin
3. Publish a new post without any tags
4. View the collection page `/untagged/`

### Technical details:

* Ghost Version: 3.11.0
* Node Version: 10.16.0
* Browser/OS: Chrome 80.0 / maxOS Catalina 10.15.3
* Database: mysql
