### ISSUE TITLE
Multi-language route filter configure questions

### ISSUE THREAD

**Issue by beautycss** [TryGhost/Ghost#11793]
Now I configure collections for multi-language pages as this tutorial(https://ghost.org/tutorials/multi-language-content/).I have three collections and now it works either if I visit http://mysite.com/cn, or http://mysite.com/en, or http://mysite.com/tw.

Then I create two "stars" pages, one is "en" tag and the other is "cn" tag.
I want to visit English page "stars" and show English page content. But when I visit http://mysite.com/en/stars, it shows 404. I tried to change the Publication Language to en, but visit http://mysite.com/en/stars is still 404, and visit http://mysite.com/stars still shows the cn page.

Questions:
1. How to configure the collections filter or page url to visit http://mysite.com/en/stars or http://mysite.com/stars and show English "stars" page?
2. I want to add a language select in frontend theme page for user to switch language, is there api to change the ghost site language with Javascript?
![image](https://user-images.githubusercontent.com/16473160/81263632-9b09be80-9072-11ea-846b-d17f4b13b4a2.png)

I'm a new user in ghost forum, the images and links are limited, so I post here.

* **Version**  3.2.0
* **Environment**  production
* **Database**  sqlite3

Here are my config.

collections:
```
routes:

collections:
  /:
    permalink: /{slug}/
    data: page.home
    template: index
    filter: 'tag:-[cn,en,tw]'
  /cn/:
    permalink: /cn/{slug}/
    data: page.home
    template: index
    filter: 'tag:cn'
  /en/:
    permalink: /en/{slug}/
    data: page.home
    template: index-en
    filter: 'tag:en'
  /tw/:
    permalink: /tw/{slug}/
    data: page.home
    template: index
    filter: 'tag:tw'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

Tag Settings:
![image](https://user-images.githubusercontent.com/16473160/81262859-2e41f480-9071-11ea-841c-6319659a4a5b.png)
![image](https://user-images.githubusercontent.com/16473160/81262872-3306a880-9071-11ea-9704-611e3a603817.png)

Page Settings:
![image](https://user-images.githubusercontent.com/16473160/81262895-3bf77a00-9071-11ea-9916-7a4ff61e6329.png)
![image](https://user-images.githubusercontent.com/16473160/81262902-3ef26a80-9071-11ea-869e-c3bbc9699592.png)
