### ISSUE TITLE
Tag meta data not working when used as `data` attribute in collection

### ISSUE THREAD

**Issue by aileen** [TryGhost/Ghost#12130]
### Issue Summary

When using a tag as a data provider in a collection like so

```yaml
collections:
  /my-collection/:
    permalink: /my-collection/{slug}/
    template: my-template
    filter: tag:tag-slug
    data: tag.tag-slug
```

the meta title and description are not being rendered within `{{ghost_head}}`. Same applies to Twitter and Facebook data.

### To Reproduce

1. Create a tag with meta data
2. Create a collection like above, pulling the tag as `data`
3. Check the `<head>` content of the rendered page. It doesn't contain any meta information

### Technical details:

* Ghost Version: 3.29.1
* Node Version: v12.18.0
