### ISSUE TITLE
Import from Wordpress - missed images 404

### ISSUE THREAD

**Issue by Bammede** [TryGhost/Ghost#12744]
Welcome to Ghost's GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

While editing the post, path to the image URL is correct there, but still the image is not found.
I also uploaded featured image manually on post and the image has been uploaded and displayed correctly, but it was not in /content/images/* directory.

### To Reproduce

Ubuntu 20.04
docker rootless
docker compose
copy images to ghost/content/images/
export/import from Wordpress to Ghost
change images path in json export file to correct one

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

There are seem to be correct images path, but images have 404 status.

console logs shows this

```
 [2021-03-08 22:01:53] WARN {{#get}} helper took 342ms to complete

  {{#get}} helper took 342ms to complete

  Error ID:
      e447fda0-8059-11eb-96c4-cbe6c8cc375e

  Error Code:
      SLOW_GET_HELPER

  Details:
      api:          v3.postsPublic.browse
      apiOptions:
        include: authors,tags
        limit:   3
      returnedRows: 3
```
docker-compose:

```
ghost:

    container_name: ghost

    image: ghost:3.42.0

    restart: unless-stopped

    depends_on:

      - mysql

    environment:

      NODE_ENV: production

      url: https://example.com

    volumes:

      - ./ghostcms/content:/var/lib/ghost/content

      - ./ghostcms/config.production.json:/var/lib/ghost/config.production.json
```
 config file:

```
{
    "url": "https://example.com",
    "server": {
        "port": 2351,
        "host": "10.5.0.6"
    },
    "database": {
        "client": "mysql",
        "connection": {
            "host": "10.5.0.7",
            "port": 3306,
            "user": "$user",
            "password": "$password",
            "database": "$databasename",
            "charset": "utf8mb4"
            }
    },
    "mail": {
        "transport": "SMTP",
        "options": {
          "service": "$service",
          "host": "$host",
          "port": 587,
          "secureConnection": true,
          "auth": {
            "user": "$user",
            "pass": "$pass"
          }
        }
    },
    "privacy": {
      "useUpdateCheck": false,
      "useGravatar": false
    }
  }
```

### Technical details:

* Ghost Version: 3.42.0
* Node Version:
* Browser/OS:
* Database: mysql
