### ISSUE TITLE
Author not included in `post.published` webhook event

### ISSUE THREAD

**Issue by arduano** [TryGhost/Ghost#13451]
### Issue Summary

I was attempting to connect Ghost to Integromat via a webhook integration triggered by Post Published event.
Everything seems to work fine, but it appears that the packet is missing an "authors" field, which seems strange considering Integromat expects there to be an authors field, and the packet does still contain other trivial metadata such as tags.

### To Reproduce

1. Create an integration with a webhook, point the webhook to a debug server
2. Create a post with one or more authors
3. Publish it
4. Check the webhook request body on the debug server, notice that it doesn't include an "authors" field while still having other metadata such as "tags".

### Technical details:

* Ghost Version: 4.16.0
* Node Version: v14.17.6
* Browser/OS: Hosted in Docker
* Database: MySQL

**Comment by matthanley** [comment]
Hey @arduano 👋🏼 

We've tested internally and the authors relation had loaded for both variations of publish / publish & send.

Theoretically this is issue may occur if the model did not have the authors relation loaded when the event was emitted. Could you provide some more information on how you're able to reproduce the error?

**Comment by arduano** [comment]
Hi, I have just reproduced it by doing the following:

1. Use this docker-compose.yml config
```yml
version: '3.1'

services:
  ghost:
    image: ghost:4.22.4-alpine
    restart: unless-stopped
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
      url: http://localhost:2368/
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password```
2. Run it, wait for it to load, navigate to `http://localhost:2368/ghost`
3. Create a basic user, skip adding more users
4. Go to integrations, create a basic webhook that is triggered by "Post published" (pointing to a debug server, I use `https://webhook.site/`)
5. Create a basic post, make sure there's at least 1 author, publish the post
6. Observe that the tags array is present (but empty), however the authors field is entirely missing.

Reproduced on ghost version 4.22.4

**Comment by arduano** [comment]
I have also reproduced it with:
```yml
version: '3.1'

services:
  ghost:
    image: ghost:4.22.4-alpine
    restart: unless-stopped
    ports:
      - 2368:2368
    environment:
      url: http://localhost:2368/
```
and
```yml
version: '3.1'

services:
  ghost:
    image: ghost:4.22.4-alpine
    restart: unless-stopped
    ports:
      - 2368:2368
    environment:
      url: http://localhost:2368/
      NODE_ENV: production
```

So far I haven't found a single configuration that does show the authors field.
