### ISSUE TITLE
AMP disallowed `!important` CSS qualifier

### ISSUE THREAD

**Issue by adamhenson** [TryGhost/Ghost#13941]
### Issue Summary

I received a notification from Google Search Console explaining that a problem with my page could cause it to not show up in search results.

> Errors can prevent your page or feature from appearing in Search results. The following errors were found on your site:

> Usage of the !important CSS qualifier is not allowed.

<img width="357" alt="Screen Shot 2022-01-09 at 10 18 02 PM" src="https://user-images.githubusercontent.com/747743/148715125-a1fe05e8-5f92-49de-aebf-c581c03f6851.png">

When viewing source of `/amp` pages... I do see the `!important` CSS qualifier used 4 times.

```css
.kg-header-card a.kg-header-card-button {
  display: flex;
 ...
  text-decoration: none !important;
 ...
}

...

.kg-header-card.kg-style-image a.kg-header-card-button,
.kg-header-card.kg-style-dark a.kg-header-card-button {
  ...
  color: #15171a !important;
}

.kg-header-card.kg-style-accent a.kg-header-card-button {
  ...
  color: var(--ghost-accent-color) !important;
}
```

I thought maybe I could fix this myself, so I downloaded the theme (Casper 4.7.2), but I couldn't find that style anywhere and also I didn't see the `amp.hbs` as described in [this post](https://ghost.org/docs/tutorials/custom-amp-themes/#how-does-amp-work-in-ghost).

### Steps to Reproduce

1: View source of this page for example: https://www.foo.software/posts/website-performance-in-2021-react-server-components-next-js-static-generation-and-linaria-zero-runtime-css/amp/

### Ghost Version

Latest (not sure - I use the "latest" tag from the Docker image)

### Node.js Version

Not sure - use the Docker Image

### How did you install Ghost?

Docker

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
