### ISSUE TITLE
For Ghost using mysql backend, Tag link on post page points to 404 page if the tag contains only one post.

### ISSUE THREAD

**Issue by d0u9** [TryGhost/Ghost#14301]
### Issue Summary

<img width="337" alt="image" src="https://user-images.githubusercontent.com/7038479/157827791-0a253b39-048d-49ce-82ec-3e5920b89ac1.png">

The red `WEB` tag should point to `/tag/web` if everything works as expected. However, for my ghost setup in which mysql8 is used as database, this tag links to 404 page instead.

<img width="89" alt="image" src="https://user-images.githubusercontent.com/7038479/157828501-c6be5ca2-5112-4198-89b2-6ec54872a95d.png">

This error only occurs when using MySQL as a backend database. Using SQLite has no problem. If I add another new post that references this tag as well, the `WEB` tag on both post pages works properly. 

### Steps to Reproduce

1. Create docker network.

    ```docker
    docker network create ghost
    ```

2. Start mysql8 container:

    ```yaml
    version: '3.9'
    services:
      ghost_mysql8:
        container_name: ghost_mysql8
        image: mysql:8
        restart: always
        networks:
          - ghost
        environment:
          MYSQL_ROOT_PASSWORD: MYSQL_PASSWD
        volumes:
          - /var/ghost/mysql8:/var/lib/mysql

    networks:
      ghost:
        external: true
        name: ghost
    ```

    ```docker
    docker-compose up -d
    ```

3. Start ghost container:

    ```yaml
    version: '3.9'
    services:
      ghost:
        container_name: ghost
        image: ghost:4-alpine
        restart: always
        environment:
          url: http://locahost
          database__client: mysql
          database__connection__host: ghost_mysql8
          database__connection__user: root
          database__connection__database: ghost
          database__connection__password: MYSQL_PASSWD
        networks:
          - ghost
        ports:
          - 80:2368/tcp
        volumes:
          - /var/ghost/website/content:/var/lib/ghost/content

    networks:
      ghost:
        external: true
        name: ghost
    ```

    ```docker
    docker-compose up -d
    ```

4. Create a new post and a new tag for this post.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/7038479/157827791-0a253b39-048d-49ce-82ec-3e5920b89ac1.png">

The red `WEB` links to 404 page.

### Ghost Version

4.38.1

### Node.js Version

v14.19.0

### How did you install Ghost?

docker image: ghost:4-alpine

### Database type

MySQL 8

### Relevant log / error output

```shell
docker image:


REPOSITORY    TAG        IMAGE ID       CREATED        SIZE
ghost         4-alpine   d853c281ff00   34 hours ago   416MB
```
```


### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
