### ISSUE TITLE
Cannot fetch assets when path other than root

### ISSUE THREAD

**Issue by mateja176** [TryGhost/Ghost#14414]
## nginx.conf - proxy

```txt
    location /blog/ {
      proxy_pass http://ghost:2368/;
      proxy_set_header Host $host:$server_port;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Protocol https;
      proxy_set_header X-Forwarded-Ssl on;
    }
```

## docker-compose - ghost service

```yml
  ghost:
    image: ghost:alpine
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure:3
    ports:
      - 3000:2368
    volumes:
      - ./ghost:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: root
      database__connection__password: ${MARIADB_ROOT_PASSWORD}
      database__connection__database: ghost
      SSL: false
      URL: http://localhost:3000/blog
      NODE_ENV: production
```

When ghost is served at `/`, everything works correctly. However, when ghost is served at `/blog`, assets such as `.css` and `.js` files cannot be found because the requests are rooted in `/`. For example:

```txt
https://localhost/public/cards.min.css?v=41e67f21f3
```

### Steps to Reproduce

- Set up `docker-compose.yml` with `nginx` and `ghost` services
- Configure nginx by setting up a docker volume or otherwise with the purpose of redirecting `/blog/` requests to ghost
- Run docker-compose up
- Navigate to the nginx origin at `/blog`

### Ghost Version

4

### Node.js Version

16

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Browser & OS version

Brave, Linux

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
