### ISSUE TITLE
🚧  Monorepo - disruption to install from source / development workflows

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#15099]
Hey everyone 👋 

A big heads up, we're actively working on changing Ghost into a monorepo - it's done but the cleanup and fallout is not handled yet.

As such, the documentation for [install from source](https://ghost.org/docs/install/source/) is out of date, and many of our tools don't work quite how they did a week ago.

If you urgently need a hand to get a source install working, let us know. Otherwise the work should be complete in another 2-3 weeks.

**Comment by ErisDS** [comment]
Some updates:

The [install from source](https://ghost.org/docs/install/source/) documentation has now been updated.

We've now merged the previously-separate [Ghost-Admin](https://github.com/TryGhost/Admin) repo into this monorepo - it lives at `ghost/admin` instead of being a submodule.

This makes it significantly easier to get a source install off the ground and to [contribute to ghost](https://github.com/TryGhost/Ghost/blob/main/.github/CONTRIBUTING.md).

One gotcha - if you need to run a `knex-migrator` command, it needs to be run from inside `ghost/core` or form the top level, you need to prefix the command with `yarn`. 

We're working on ironing out all the issues, but if you spot anything that isn't working please let us know!

**Comment by rbtnn** [comment]
Excuse me. How we make a zip file from this Monorepo? I used following commands and installed the custom build.

```
yarn build release
ghost install --zip path/to/file.zip
```

**Comment by daniellockyer** [comment]
Hey @rbtnn 🙂 We're moving away from zip files in favor of .tgz file produced by `npm pack`. There's still a bit of friction, but the easiest solution is:

1. From the latest Ghost `main`, run `npm pack` inside `ghost/core` => this produces a ghost-X.X.X.tgz file in `ghost/core`
2. Ensure you have Ghost-CLI, which supports importing .tgz files
3. `ghost install local --archive path/to/archive.tgz`

**Comment by rbtnn** [comment]
@daniellockyer  Thank you so much for your advice! I'll wait until this Monorepo is stable becuase I customaize both TryGhost/Ghost and TryGhost/Admin.

**Comment by daniellockyer** [comment]
TryGhost/Admin has been merged into this repository under `ghost/admin` - https://github.com/TryGhost/Ghost/tree/main/ghost/admin 🙂

**Comment by rbtnn** [comment]
Are .tgz file and .zip file produced by `npm pack` in the same directory structure?

**Comment by daniellockyer** [comment]
They are not - the .zip has all of the files in the top-level, but the .tgz has them inside `package/` as `npm pack` and NPM packages expect. That said, `.zip` is deprecated and all tooling will focus on `.tgz` from now on

**Comment by rbtnn** [comment]
>.zip is deprecated and all tooling will focus on .tgz from now on
I see.

**Comment by JuanDelgadillo** [comment]
Hey folks!

I faced the same issue generating the custom `zip` file for my site after the Ghost migration into a monorepo.

I created a Github release action that helps me convert the build file from `tgz` to `zip`.

I will be using it till Ghost team finishes ironing out remaining issues from the monorepo, and `zip` to `tgz` transitions.

This is the Github action in case you are wondering how it works:
```yaml
name: Release
on:
  push:
    tags:
      - '*'
jobs:
  automate:
    runs-on: ubuntu-18.04
    env:
      RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REF_NAME: ${{ secrets.GITHUB_REF_NAME }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: true
      - uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: '16.14.2'
          cache: yarn

      - run: yarn

      - run: npx --yes daniellockyer/monobundle
        working-directory: ghost/core
      
      - run: npm pack
        working-directory: ghost/core

      - run: mkdir -p .dist/release/
        working-directory: ghost/core

      - run: tar -xvzf "./ghost-$(echo $GITHUB_REF_NAME | tr -d "v").tgz" -C .dist/ 
        working-directory: ghost/core

      - run: cd .dist/package && zip -r "../release/Ghost-$(echo $GITHUB_REF_NAME | tr -d "v").zip" ./*
        working-directory: ghost/core

      - name: Check out action
        uses: actions/checkout@v2
        with:
          repository: juandelgadillo/action-ghost-release
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/action-ghost-release
      - name: Run my action
        uses: ./.github/actions/action-ghost-release

```

You might need to adapt it to your needs but the more important commands are:
- `yarn`
  - This install all npm dependencies for Ghost core and Admin
- `npx --yes daniellockyer/monobundle`
  - This packages required dependencies for the project to work properly and places them under `components` folder
- `npm run pack`
  - This generates the `tgz` file
- `tar -xvzf "./ghost-$(echo $GITHUB_REF_NAME | tr -d "v").tgz" -C .dist/ `
  - This decompress the `tgz` file
- And, `cd .dist/package && zip -r "../release/Ghost-$(echo $GITHUB_REF_NAME | tr -d "v").zip" ./*`
  - This generates a `zip` file that ghost-cli understands
  
  The variable `$GITHUB_REF_NAME` references my own semver version.
