### ISSUE TITLE
Compatibility with Planetscale cloud - a managed MySQL database

### ISSUE THREAD

**Issue by Southclaws** [TryGhost/Ghost#15779]
### Issue Summary

I had an internal debate over whether this was classified as a "bug" or not. Planetscale claims to be a MySQL-compatible database (akin to what CockroachDB is to Postgres?) so I figured I could possibly run an engineering blog on this using Ghost in future.

I jumped through a few hoops to get things running but finally hit a blocker that seems impassable without tweaking how Ghost is running migrations.

```
blog-ghost-1  | [2022-11-07 18:46:51] WARN Database state requires initialisation.
blog-ghost-1  | [2022-11-07 18:46:51] ERROR CREATE DATABASE `blog` CHARACTER SET utf8mb4; - Can't create database 'blog'; database exists
blog-ghost-1  | 
blog-ghost-1  | CREATE DATABASE `blog` CHARACTER SET utf8mb4; - Can't create database 'blog'; database exists
```

It seems Ghost is trying to create a database before it creates the tables. Unfortunately, I cannot delete the database within a Planetscale instance as it's managed by the system itself and locked from editing, even from an account with admin permissions.

It would be great to see if this would be possible to run the migration setup without the need to create the database - perhaps Ghost can "create if not exists" instead?

### Steps to Reproduce

Start by creating a DB on the Planetscale free tier, name this database "blog".

Next, run this Docker compose instance of Ghost locally:

```yaml
version: '3'

services:
  ghost:
    image: ghost:5.22.4-alpine
    restart: "on-failure"
    ports:
      - 8080:2368
    environment:
      database__client: "mysql"
      database__connection__database: "blog"
      database__connection__host: "aws-region-name-etc.connect.psdb.cloud"
      database__connection__password: "pscale_pw_XYZ..."
      database__connection__user: "..."
      database__connection__ssl__rejectUnauthorized: "true"
      database__connection__ssl__secureProtocol: "TLSv1_2_method"
```

For now I'll have to stick with self-managed MySQL instance on Fly.io (very unfortunate to see sqlite support get dropped)

### Ghost Version

5.22.4

### Node.js Version

whatever is in the image

### How did you install Ghost?

see above

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
