### ISSUE TITLE
oder: primary_tag.name asc does not work

### ISSUE THREAD

**Issue by ahoiroman** [TryGhost/Ghost#16076]
### Issue Summary

Hello,

having this collection defined in the `routes.yaml`, ordering by the primary_tag does not have any effect:

```
collections:
  # Homepage
  /:
    permalink: /{slug}/
    template: index
    order: primary_tag.name asc, published_at asc
    filter: tag:-hash-blog
```

### Steps to Reproduce

Add the `order`-directive as stated above and see the result.

### Ghost Version

5.26.4

### Node.js Version

v16.19.0

### How did you install Ghost?

ghost-cli on ubuntu 22.04

### Database type

MySQL 8

### Relevant log / error output

```shell
Ghost-CLI version: 1.23.1
Ghost version: 5.26.4
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
