### ISSUE TITLE
Postgres driver doesn't get installed automatically

### ISSUE THREAD

**Issue by mesudip** [TryGhost/Ghost#16455]
### Issue Summary

ghost-5 doesn't automatically install the `pg` dependency.

Additionally, the it's trying to install pg with `npm` but the distribution contains `yarn.lock` file. It should install it with `yarn` instead.

### Steps to Reproduce

```
  ghost:
       image: ghost:5-alpine
      restart: always
      networks:
        - postgres
      ports:
        - 8080:2368
      environment:
        # see https://ghost.org/docs/config/#configuration-options
        database__client: postgres
        database__connection__host: postgres
        database__connection__user: postgres
        database__connection__password: some easy password
        database__connection__database: site_blog
        # this url value is just an example, and is likely wrong for your environment!
        url: https://kuberide.sireto.dev
        VIRTUAL_HOST: https://example.com
        # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
        NODE_ENV: development
```

### Ghost Version

ghost:5-alpine

### Node.js Version

from docker

### How did you install Ghost?

docker

### Database type

Other

### Relevant log / error output

```shell
[2023-03-21 07:24:59] INFO Ctrl+C to shut down
[2023-03-21 07:24:59] INFO Ghost server started in 0.328s
Knex: run
$ npm install pg --save
Cannot find module 'pg'
Require stack:
- /var/lib/ghost/versions/5.39.0/node_modules/knex-migrator/node_modules/knex/lib/dialects/postgres/index.js
- /var/lib/ghost/versions/5.39.0/node_modules/knex-migrator/node_modules/knex/lib/dialects/index.js
- /var/lib/ghost/versions/5.39.0/node_modules/knex-migrator/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /var/lib/ghost/versions/5.39.0/node_modules/knex-migrator/node_modules/knex/lib/knex-builder/Knex.js
- /var/lib/ghost/versions/5.39.0/node_modules/knex-migrator/node_modules/knex/lib/index.js
- /var/lib/ghost/versions/5.39.0/node_modules/knex-migrator/node_modules/knex/knex.js
- /var/lib/ghost/versions/5.39.0/node_modules/knex-migrator/lib/database.js
- /var/lib/ghost/versions/5.39.0/node_modules/knex-migrator/lib/index.js
- /var/lib/ghost/versions/5.39.0/core/server/data/db/state-manager.js
- /var/lib/ghost/versions/5.39.0/core/boot.js
- /var/lib/ghost/versions/5.39.0/ghost.js
- /var/lib/ghost/versions/5.39.0/index.js
Error: Cannot find module 'pg'
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
