### ISSUE TITLE
Card assets files aren't generated by Ghost when using the `include` keyword

### ISSUE THREAD

**Issue by benjaminrancourt** [TryGhost/Ghost#16652]
### Issue Summary

According to the [CardAssetService file](https://github.com/TryGhost/Ghost/blob/main/ghost/core/core/frontend/services/card-assets/service.js#L33-L38), a theme developer could specify the list of assets files (JavaScript and CSS) they want Ghost to be generate.

I don't know if I'm the only one having this bug, but when I add the `card_assets.include` keyword in my `package.json` file, the `cards.min.css` and `cards.min.js` files aren't generated by Ghost.

```json
{
  "config": {
    "card_assets": {
      "include": [
        "audio",
        "header"
      ]
    }
}
```

And I tried to debug and see the generated globs [here](https://github.com/TryGhost/Ghost/blob/main/ghost/core/core/frontend/services/card-assets/service.js#L104), but I haven't been able to see any relevant debug logs. Maybe I'm doing something wrong with my debug configuration? 🤔

Here is my `docker-compose` file with the `DEBUG` variable set to `card-assets`.

```yaml
version: '3.8'

services:
  ghost:
    container_name: "ghost"
    environment:
      NODE_ENV: 'development'
      server__port: 2368
      url: 'http://localhost:2368'
      DEBUG: 'card-assets'
    image: ghost:5.43.0-alpine
    ports:
      - "2368:2368"
    volumes:
      - './.content/config.production.json:/var/lib/ghost/config.production.json'
      - './.content/data:/var/lib/ghost/content/data'
      - './.content/images:/var/lib/ghost/content/images'
      - './.content/logs:/var/lib/ghost/content/logs'
      - './.content/settings:/var/lib/ghost/content/settings'
      - './:/var/lib/ghost/content/themes/casper'
```

Here are some screenshots:

**With `exclude` (working as expected):**
![image](https://user-images.githubusercontent.com/7907713/232500014-2df20a25-37ac-42f0-bf92-44143d305caa.png)

**With `include` (not working):**
![image](https://user-images.githubusercontent.com/7907713/232500251-6fe8c344-16e8-4d0b-a892-cec1b2aa72eb.png)

### Steps to Reproduce

1. Specify the `card_assets.include` keyword in your theme `package.json`.

```json
{
  "config": {
    "card_assets": {
      "include": [
        "audio",
        "header"
      ]
    }
}
```

2. Restart Ghost
3. Open your website and check if the `cards.min.css` and `cards.min.js` files were generated and included by Ghost.

### Ghost Version

5.43.0

### Node.js Version

v18.15.0

### How did you install Ghost?

Docker

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
