### ISSUE TITLE
Lexical kg-cards missing on website after ghost update with zip

### ISSUE THREAD

**Issue by ASAMedia** [TryGhost/Ghost#18948]
### Issue Summary

I updated my custom Ghost to version 5.71.2.
It runs fine in development via `yarn dev`, but upgrading the 5.70 docker with an .tgz file from `yarn archive` brings up some problems.
When editing existing posts (mobiledoc) and saving them with the new editor (lexical) ALL images and other kg-cards will not show up anymore on the website of this post.
There is not a single error in webconsole or `docker-compose logs -f` during/saving editing or while upgrading ghost.
When running the original 5.71 docker image or `yarn dev` everything runs fine without this issue.

~Looking into the sqlite database, I'll found that the lexical code is complete with the image.~

So it seems like an update problem, that I cant narrow down without some help.
Any idea how to fix this?

### Steps to Reproduce

1. create the following DOCKERFILE
``` 
FROM ghost:5.71.0-alpine
WORKDIR /var/lib/ghost
COPY ./ghost-5.71.2.tgz /var/lib
RUN apk add --no-cache git
USER node
RUN yarn --version
RUN yarn cache clean
RUN rm -rf node_modules
RUN yarn
RUN chmod -R 00775 /var/lib/ghost/content &&\
    ghost update --force --zip /var/lib/ghost-5.71.2.tgz
RUN chmod -R 00775 /var/lib/ghost/content
```
2. create the docker-compose.yml
```
version: '3.1'

services:

  lfg-ghost:
    build: .
    container_name: lfg-ghost
    restart: always
    ports:
      - 2368:2368
    volumes:
      -  ./content:/var/lib/ghost/content
      -  ./.env:/var/lib/ghost/.env
    environment:
      NODE_ENV: development
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      url: 
      mail__transport: SMTP
      mail__from: 
      mail__options__service: SMTP
      mail__options__host: 
      mail__options__port: 587
      mail__options__auth__user: 
      mail__options__auth__pass: 
```
3. Download the release file from [here](https://github.com/ASAMedia/Ghost-LFG/releases/tag/5.71.2-lfg.19)
4. run `sudo docker-compose build`, `sudo docker-compose up -d` 

### Ghost Version

5.71.2

### Node.js Version

18

### How did you install Ghost?

docker-compose

### Database type

SQLite3

### Browser & OS version

Win 11/Ubuntu 20/Chrome/Firefox/Edge

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
