### ISSUE TITLE
why is a "url" required

### ISSUE THREAD

**Issue by Tinger-X** [TryGhost/Ghost#19250]
### My envs
**Docker version**: 24.0.2, build cb74dfc
**Docker Compose version**: v2.20.0
**LSB Version**:    :core-4.1-amd64:core-4.1-noarch
**Distributor ID**: AlibabaCloud
**Description**:    Alibaba Cloud Linux release 3 (Soaring Falcon)
**Release**:        3
**Codename**:       SoaringFalcon

### My docker-compose.yml
```yml
version: '3'
services:
  Ghost:
    image: ghost:4-alpine
    container_name: Ghost
    restart: unless-stopped
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: MySQL
      database__connection__user: ghost
      database__connection__password: <my-mysql-password>
      database__connection__database: ghost
    volumes:
      - ./:/var/lib/ghost
networks:
  default:
    name: <MyDockerNetName>
    external: true
```

### My config.production.json
```json
{
  "url": "https://blog.<mydomain.com>/",
  "server": {
    "port": 80,
    "host": "0.0.0.0"
  },
  "database": {
    "client": "sqlite3",
    "connection": {
      "filename": "/var/lib/ghost/content/data/ghost.db"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/lib/ghost/content"
  }
}
```

### My nginx/conf/blog.conf
```` conf
server {
  listen 80;
  listen [::]:80;
  server_name blog.<mydomain.com>;

  # rewrite to https:
  rewrite ^(.*)$ https://$host$request_uri;
}
server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name blog.<mydomain.com>;
  include <my-ssl-cert-path>;

  location / {
    proxy_pass http://Ghost/;
  }
}
````

### My existed prepare
1. create a docker network named as &lt;MyDockerNetName&gt;
2. use docker to run nginx-server as "Nginx", mysql-server as "MySQL" in docker container, both joined &lt;MyDockerNetName&gt;
3. run ghost in docker container and copy ghost:/var/lib/ghost/* to my workdir(/srv/ghost)
4. modify config.production.json as before
5. start ghost server in docker container

### Problem I meet
when I visit ```https://blog.<mydomain.com>```, it will redirect to ```https://ghost/```，but my other service configured in the same way will never do like this.

### Steps to Reproduce

1. user visit ```https://blog.<mydomain.com>/```
2. nginx got a request and pass it to ```http://Ghost/``` in the same docker network
3. ghost running in docker container received request passed from nginx, deal its business and make some response

I just don't know why there need a "url" in configuration, and why the service make a 301 response to ```https://ghost/```

### Running log
```
[2023-12-06 08:03:51] INFO Ghost is running in production...
[2023-12-06 08:03:51] INFO Your site is now available on https://blog.<mydomain.com>/
[2023-12-06 08:03:51] INFO Ctrl+C to shut down
[2023-12-06 08:03:51] INFO Ghost server started in 0.447s
[2023-12-06 08:03:51] INFO Database is in a ready state.
[2023-12-06 08:03:51] INFO Ghost database ready in 0.731s
[2023-12-06 08:03:54] INFO Ghost booted in 2.991s
[2023-12-06 08:03:54] INFO Adding offloaded job to the queue
[2023-12-06 08:03:54] INFO Scheduling job update-check at 34 43 11 * * *. Next run on: Wed Dec 06 2023 11:43:34 GMT+0000 (Coordinated Universal Time)
[2023-12-06 08:04:18] INFO "GET /" 301 10ms
```

### Ghost Version

4.14.0

### Node.js Version

v14.17.6

### How did you install Ghost?

docker pull ghost:4-alpine

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
