### ISSUE TITLE
Post editor title/heading font does not match rendered font

### ISSUE THREAD

**Issue by huzaifahj** [TryGhost/Ghost#20225]
### Issue Summary

If the font for post titles/headings when rendered finally to the user is a serif font, then the editor should allow editing the post using a serif font.

Marked as a bug because this discrepancy causes frustration and breaks the seamlessness in the UX of writing posts. The font should match the current theme's exact font.

### Steps to Reproduce

1. Change site font to serif
2. Visit post editor

### Ghost Version

Latest

### Node.js Version

18

### How did you install Ghost?

Self hosted

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by huzaifahj** [comment]
Issue changed as I've noticed the content font does match, but the title/heading fonts do not.

Extra CSS is needed for the dashboard, inserted using a Chrome extension:

```css
@import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap');

.gh-editor-title {
	font-family: "EB Garamond"!important;
	font-weight: 550!important;
}
```
