### ISSUE TITLE
SiteRouter is null - TypeError: Cannot read properties of null (reading 'handle')

### ISSUE THREAD

**Issue by TigerC10** [TryGhost/Ghost#20723]
### Issue Summary

I don't know why this is happening, but _somehow_ the SiteRouter is `null` when rendering the frontend.  Only when rendering the frontend.  When I look at posts in the frontend, I get a 500 error.  Post editor in the backend displays perfectly.

I've traced the issue to the `ParentRouter.js`:
https://github.com/TryGhost/Ghost/blob/v5.89.0/ghost/core/core/frontend/services/routing/ParentRouter.js#L90

I'm almost completely certain this has to do with the migration of content, but I don't know where to look for content that didn't migrate properly.

### Steps to Reproduce

1. Import Content From Ghost 2/3/4

### Ghost Version

5.89.0

### Node.js Version

18.20.4

### How did you install Ghost?

Docker Image

### Database type

MySQL 8

### Browser & OS version

Chrome 127 (MacOS Sonoma)

### Relevant log / error output

```shell
[2024-08-06 22:20:12] ERROR "GET /blog/test/" 500 10ms

An unexpected error occurred, please try again.

"Cannot read properties of null (reading 'handle')"

Error ID:
    0c960df0-5442-11ef-9f84-b135dd8aea32

Error Code: 
    UNEXPECTED_ERROR

----------------------------------------

TypeError: Cannot read properties of null (reading 'handle')
    at prepareError (/var/lib/ghost/versions/5.89.0/node_modules/@tryghost/mw-error-handler/lib/mw-error-handler.js:113:19)
    at CollectionRouter._respectDominantRouter (/var/lib/ghost/versions/5.89.0/core/frontend/services/routing/ParentRouter.js:90:20)
    at paramCallback (/var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:415:7)
    at param (/var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:395:5)
    at Function.process_params (/var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:421:3)
    at next (/var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:280:10)
    at CollectionRouter._prepareEntryContext (/var/lib/ghost/versions/5.89.0/core/frontend/services/routing/CollectionRouter.js:123:9)
    at trim_prefix (/var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:328:13)
    at /var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:346:12)
    at next (/var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:280:10)
    at /var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:646:15
    at next (/var/lib/ghost/versions/5.89.0/node_modules/express/lib/router/index.js:265:14)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cmraible** [comment]
Hi @TigerC10 — I'd like to confirm that it's the content import that's causing this problem. Are you able to create a new post from scratch in this state? If so, would you mind creating & publishing a new post and seeing if you get the same error?

**Comment by cmraible** [comment]
While you're at it, could you share if you have any custom configuration options enabled? No need to share the whole config, just curious if you've enabled anything beyond the default config. Thanks 🙏🏼

**Comment by TigerC10** [comment]
Yes, creating and publishing new posts does not help.

Nothing special in the `routes.yaml`:
```yaml
routes:

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

**Comment by cmraible** [comment]
> creating and publishing new posts does not help.

Thanks, that's super helpful! This leads me to believe it may not be an issue with content migration — mostly likely that would only apply to the migrated posts, but a new post created from scratch would probably be unaffected by any content migration issues.

> Nothing special in the `routes.yaml`:

Good to know! However I was referring to Ghost's configuration — depending on how you're running your docker image, this might be mounted into the container as a JSON file (e.g. `config.production.json`), or it might be passed to the container as environment variables.<br><br>Specifically, I'm wondering if you happen to have opentelemetry enabled, as it's a WIP and has caused similar errors to what you're seeing here.

**Comment by cmraible** [comment]
It might also be helpful to know more about how your running the docker image — e.g. are you manually doing a `docker run ghost ….`, or using docker compose, kubernetes, etc?

**Comment by TigerC10** [comment]
It's run through Docker Compose.  Running on a single VM in GCP.  

```yaml
version: '3.1'
services:
  ghost:
    container_name: ghost
    image: ghost:5.89.0
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: <redacted>
      database__connection__password: <redacted>
      database__connection__database: <redacted>
      url: "https://<redacted>/blog"
      mail__transport: SMTP
      mail__options__host: <redacted>
      mail__options__port: "465"
      mail__options__secure: "true"
      mail__options__auth__user: <redacted>
      mail__options__auth__pass: <redacted>
    volumes:
      - "/mnt/ghost-data/content:/var/lib/ghost/content"
    depends_on:
      - mysql
      - nginx
  mysql:
    container_name: mysql
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    restart: always
    command: ["/cloud_sql_proxy", "-instances=<redacted>:<redacted>:<redacted>=tcp:0.0.0.0:3306"]
    ports:
      - 3306:3306
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - "/mnt/ghost-data/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/mnt/ghost-data/content:/var/lib/ghost/content"
```

Since I'm using the ghost image from Dockerhub, I don't really do much with the config json.  here's that:
```json
{
  "url": "http://localhost:2368",
  "server": {
    "port": 2368,
    "host": "::"
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/lib/ghost/content"
  }
}
```
