### ISSUE TITLE
_🛠️ Refactor suggestion_

### ISSUE THREAD

**Issue by nodoubtz** [TryGhost/Ghost#22602]
_🛠️ Refactor suggestion_

**Align with Ghost's build practices**

This workflow uses npm and webpack directly, but the PR objectives mention Ghost's standard commands use yarn. Also, there's no caching configured which will slow down builds.

```diff
 - name: Build
   run: |
-    npm install
-    npx webpack
+    yarn install --frozen-lockfile
+    yarn build
+    yarn lint
+    yarn test:all
```

Consider adding dependency caching:

```yaml
- name: Cache dependencies
  uses: actions/cache@v3
  with:
    path: '**/node_modules'
    key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
```

_Originally posted by @coderabbitai[bot] in https://github.com/TryGhost/Ghost/pull/22601#discussion_r2009394695_
