### ISSUE TITLE
icon.scss - 'camera' appears twice

### ISSUE THREAD

**Issue by mankittens** [TryGhost/Ghost#4878]
On lines 155 & 167, there is each a variable named '$i-camera' with differing values (though the icons look the same).

Lines 331 & 367 refer to '$i-camera' to make css rules.

**Comment by halfdan** [comment]
For reference: https://github.com/TryGhost/Ghost/blob/master/core/client/assets/sass/modules/icons.scss#L155

This is a good catch. /cc @PaulAdamDavis

**Comment by PaulAdamDavis** [comment]
Well spotted :)

As a visual reference, this is both icons.
![screen shot 2015-02-02 at 11 53 55](https://cloud.githubusercontent.com/assets/390392/6000145/459c49ee-aad2-11e4-93a3-e9457f0ebb87.png)

I agree this should be removed, but I don't think it's worth doing on its own. IMO, this should be removed as part of another CSS-related chunk of work. Reason being, it's very similar to a typo fix, which we don't generally do pull requests for on their own.

**Comment by mankittens** [comment]
Quick question about SASS style for this repo. What's the preference here for autogenerating rules? I ask because I noticed this bug when refactoring the Icon Variables and Icon Classes sections using maps:

```
//
// Icon Variables
// --------------------------------------------------

$icons: (
placeholder:     \e018,
ghost:           \e000,
ghost-logo:      \e600,
...
);

//
// Icon Classes
// --------------------------------------------------

@each $key, $content in $icons {
    .icon-#{$key}:before {
        content: '#{$content}';
    }
}
```

Thanks.

**Comment by PaulAdamDavis** [comment]
We're not using maps at the moment, mostly due to lack of support in the version of Libsass we were using. I've just opened #4884 which adds this support :)

Maps seems to work then, and your snippet above generated just fine. 

```css
.icon-placeholder:before {
  content: '\e018'; }

.icon-ghost:before {
  content: '\e000'; }

.icon-ghost-logo:before {
  content: '\e600'; }
```

I've liked the idea of using a map for these icon classes, but gave up early on due to lack of support. So, but :+1: from me for this!

However, one thing to keep in mind is that we do use the variables in some mixins [components/notifications.scss#L52](https://github.com/TryGhost/Ghost/blob/1cdafae8d96d529b5414a1f2a0553204be0f8e32/core/client/assets/sass/components/notifications.scss#L52), so you'll also need to create a function that gets the variable by name. Something like this: (untested)

```scss
@function geticon($icon-name, $type: 'value'){
  $theicon: map-get($icons, $icon-name);
  @if ($type == 'string') {
      $finalicon: '#{$theicon}';
  } @else {
      $finalicon: $theicon;
  }
  @return $finalicon;
}

.thing-as-value {
  @include icon(geticon('ghost', 'value'), 2rem, #f00);
}

.thing-as-string {
  content: geticon('ghost', 'string');
}
```

Which generates:

```css

.thing-as-value:before {
  content: '\e000';
  font-size: 2rem;
  color: #f00; }

.thing-as-string {
  content: '\e000'; }
```
