### ISSUE TITLE
Code injection CSS syntax highlighting is impossible to read 

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5179]
![screen shot 2015-04-22 at 20 39 47](https://cloud.githubusercontent.com/assets/120485/7282351/1fa85e68-e938-11e4-845c-961c7893db2e.png)

**Comment by ErisDS** [comment]
Do you want to switch to a different theme or add an override for that one style?

**Comment by acburdine** [comment]
If you want I can create a github-esque theme for CodeMirror, but then again it results in having an extra file living somewhere in the repo.

**Comment by PaulAdamDavis** [comment]
Depending how many parts of the syntax highlighting are hard to read, it might be better to overide them in [styles/layouts/settings.scss#L546](https://github.com/TryGhost/Ghost/blob/master/core/client/app/styles/layouts/settings.scss#L546). Nesting inside `.settings-code-editor` ensures our styles get used, not CodeMirror's.

```css
.settings-code-editor {
    // properties... 
    
    .cm-s-xq-light span.cm-meta {
        color: #000;
    }
}
```
