### ISSUE TITLE
Styling on Inputs Poorly Affects Checkboxes

### ISSUE THREAD

**Issue by andrewvaughan** [TryGhost/Ghost#7471]
### Issue Summary

The style parameters are too broad for "input" types, negatively affecting check boxes (makes them unreadable).  Specifically this block, once compiled, in `screen.css`:

```css
textarea, select, input {
    width: 260px;
    padding: 6px 9px;
    margin: 0 0 5px 0;
    outline: 0;
    font-family: 'Open Sans', sans-serif;
    font-size: 1.6rem;
    font-weight: 100;
    line-height: 1.4em;
    background: #fff;
    border: #e7eef2 1px solid;
    border-radius: 4px;
    box-shadow: none;
    -webkit-appearance: none;
}
```

Being more specific (e.g., `input[type=text], input[type=password]`) on the CSS should prevent overlap of other types of inputs.

### Steps to Reproduce

Put this in any post:

```html
<input type="checkbox" />
```

### Technical details:

* Ghost Version: 0.11.1
* Node Version: 0.12.3
* Browser/OS: Chrome/PC
