### ISSUE TITLE
Large (width/height) images (in posts and as cover images) don't resize for mobile

### ISSUE THREAD

**Issue by grantwinney** [TryGhost/Ghost#8701]
### Issue Summary

I've got quite a few posts with images that are screen shots, so they're fairly large in dimension. They're not resizing automatically when I resize the desktop browser, nor when I view on a mobile device.

### Steps to Reproduce

1. Add an image with a large width (1000px for instance) to a post.
2. Resize the desktop browser window or view on a mobile device.
3. Observe that the image does not resize.

I did not notice this behavior in the 0.11.1 release - it only started in rc.1.

### Proposed Resolution?

I managed to fix it but wasn't sure what the intent was, so I didn't make a PR.

The `screen.css` file defines this block of css:

```css
.post-full-content img {
    display: block;
    margin: 1.5em auto;
    max-width: 1040px;
}
```

I overrode it in a custom css file to change the max-width:

```css
.post-full-content img {
    max-width: 100%;
}
```

This had the added benefit of fixing the cover images too. They wouldn't resize either, so that resizing the browser or viewing on mobile only displayed the top-left corner of the image, instead of resizing it appropriately.

### Technical details:

* Ghost Version: 1.0.0.-rc.1
* Node Version: v6.11.1
* Browser/OS:
  * Chrome Version 59.0.3071.115 (Official Build) (64-bit) / OSX 10.12.5
  * Chrome 58.0.3029.83/Android 5.1
* Database: MySql
