### ISSUE TITLE
docker compose linuxserver/letsencrypt & ghost

### ISSUE THREAD

**Issue by matjazmav** [TryGhost/Ghost#9221]
I'm trying to proxy `ghost` through `letsencrypt` service (linuxserver/letsencrypt basically nginx) and handle SSL only on proxy side. Ghost should be available over https://subdomain.duckdns.org/blog. I have problems to configure this combination. I was playing with different combinations of `proxy_pass` (nginx config) and `url` (ghost env variable) but somehow can figure it out. What am I missing?

**./nginx-sites/default.conf**
```conf
server {
        listen 443 ssl;

        server_name subdomain.duckdns.org;

        # SSL configuration here

        client_max_body_size 0;

        proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
                return 301 /blog/;
        }

        location /blog/ {
                proxy_pass http://blog:2368/;
        }
}
```

**./docker-compose.yml**
```yml
version: '3'

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - data_letsencrypt:/config
      - ./nginx-sites:/config/nginx/site-confs:ro
    environment:
      - EMAIL=address@gmail.com
      - URL=duckdns.org
      - SUBDOMAINS=subdomain
      - ONLY_SUBDOMAINS=true
      - TZ=Europe/London
    cap_add:
      - NET_ADMIN
    links:
      - blog
    restart: on-failure:5

  blog:
    image: ghost
    volumes:
      - data_blog:/var/lib/ghost/content
    environment:
      - url=https://subdomain.duckdns.org/blog/
    restart: on-failure:5
```
