### ISSUE TITLE
Apply appropriate style to calendar selector in Dark mode

### ISSUE THREAD

**Issue by tpiros** [TryGhost/Ghost#9244]
Not really a bug, more like a stylistic change: when using the dark mode, the calendar for the post schedular displays the name of the days using a near-black colour (). It makes it impossible to read the name of days.

```css
.ember-power-calendar-weekdays {
  color: #333
}
```

Should probably be just `#eee` or even `#fff`.
