### ISSUE TITLE
Moved Permanently. Redirecting to https://XXXXX

### ISSUE THREAD

**Issue by linxyfe** [TryGhost/Ghost#9772]
Hi, I am currently running ghost on docker,  with a load balancer in front of it,  and I get this issue which I don't understand: 

```
ubuntu@qcloud:~/data/compose/ghost$ curl https://blog.xoxox.io
Moved Permanently. Redirecting to https://ghost/
```
the following is the my settings of everything

Ghost Version: docker image:  ghost:1-alpine

Ghost compose file:
```
blog:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ~/data/docker_volumes/ghost/content:/var/lib/ghost/content
    environment:
      - MAIL_FROM=will@xoxox.io
      - url=https://blog.xoxox.io
```

Nginx compose file:
```
proxy:
      image: nginx
      ports:
       - "80:80"
       - "443:443"
      volumes:
       - ./certs:/etc/nginx/certs
       - ./conf.d/blog.xoxox.io.conf:/etc/nginx/conf.d/blog.xoxox.io.conf
```

Nginx conf:
```
upstream ghost  {
    server qcloud.xoxox.io:2368;
}
server {
	server_name blog.xoxox.io;
	listen 80;
	return 301 https://$host$request_uri;
}
server {
	server_name blog.xoxox.io;

	listen 443 ssl http2;

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_certificate /etc/nginx/certs/blog.xoxox.io.crt;
	ssl_certificate_key /etc/nginx/certs/blog.xoxox.io.key;

	client_max_body_size 0;

	location / {
		proxy_pass http://ghost;
	}
}
```

PS: if I remove url environment variable, it goes right,
```
      - url=https://blog.xoxox.io
```
but the blog site does not handle links right.
