### ISSUE TITLE
Errors when uploading routes.yaml with unknown resource

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#9870]
### To Reproduce

create a `routes.yaml` like below

```yaml
routes:

collections:
  /:
    permalink: '/{slug}/'
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
  teste: /teste/{slug}/
```

Attempt to upload it in the admin

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

We could either send back a 400 and say the routes.yaml is not valid, or we could ignore the non existent resource and skip over it.    

### Technical details:

* Ghost Version: 2.1.2
* Node Version: all
* Browser/OS: all
* Database: doesn't matter
