### ISSUE TITLE
Inverse tag filtering in dynamic routing works incorrectly

### ISSUE THREAD

**Issue by vladimir-vg** [TryGhost/Ghost#9950]
### Issue Summary

Collection route renders page with zero items, when inverse tag filter is specified.

### To Reproduce

1. Create tag with "en" slug.
2. Attach this tag to some of the stories
3. Upload a following routes.yaml. Guided by this page: https://help.ghost.org/article/112-multi-language-content

```
routes:

collections:
  /:
    permalink: /{slug}/
    filter: tag:-en
    template:
      - index
  /en/:
    permalink: /en/{slug}/
    filter: tag:en
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
4. Restart Ghost (just in case).
5. Open /en/ -- see stories that were tagged at step 2. All as expected.
6. Open / -- no items, empty page. Expected to see all stories that are not tagged with "en". 

If I rewrite `filter: tag:-en` as `filter: tag:-[en]` it has same effect.

Interestingly, if I comment out `filter: tag:-en` for the `/` route, then behavior is reversed. Empty list for `/en/` (unexpected) and all stories for `/` (expected).

### Technical details:

* Ghost Version: 2.2.0
* Node Version: v6.9.4
* Browser/OS: Ubuntu 14.04 64bit
* Database: MySQL Ver 14.14 Distrib 5.5.61, for debian-linux-gnu (x86_64) using readline 6.3

No errors in `/var/www/ghost/content/logs/http___vladimir_vg_me__production.error.log`. Just empty file.

This is the website: http://vladimir-vg.me

**Comment by kirrg001** [comment]
@vladimir-vg Hey :) Will look at your report on Monday!

**Comment by vladimir-vg** [comment]
Thanks! If you need more information don't hesitate to ask.

**Comment by kirrg001** [comment]
I can't reproduce this 🤔 

I tagged two posts with `en`. `/en/` shows 2 posts.
`/` shows the rest.

**Comment by cotko** [comment]
@kirrg001 I just wanted to report same thing.
I made 4 new posts, 2 tagged as *de* language and *two without any tags* (which would be a default language). Using *-de* does not pick up the two without any tags, it seems as if query joins tags to the posts and if posts are not tagged at all, then they are also filtered out, although it would make sense that they should be picked up, since they do not contain the *de* tag.

**Comment by kirrg001** [comment]
@cotko Could you please share your routes.yaml file? Thanks 👍

**Comment by cotko** [comment]
@kirrg001 Just tried with the one @vladimir-vg posted above and it's the same. If you go and edit some of the posts and just remove all tags from the posts, you will see that they disappear from the blog at the default route, where **tag:-en** is used. Then if you tag those posts again with anything but *en* they appear again.

**Comment by kirrg001** [comment]
Thanks. Will play with this. I guess it's caused by having posts with no tags at all 🤔

**Comment by kirrg001** [comment]
Okay had some more time to reproduce now. Can confirm, inverse filtering does not work correctly.

I think i even see two bugs here.

This filter troubles: `filter=tag:-en`

1. The SQL query does not respect posts which have no tags. The SQL query does not return posts with no tags, but it should IMO.

2. The SQL query has problems when the post is tagged with multiple tags. e.g. "test" has two tags "en" and "beautiful". The first tag is en, but the second is not en. The SQL query must say "if one tag is en, then do not return the result". You won't see these post when you serve the page, because Ghost will filter them out, because they are owned by a different collection.

@ErisDS Could you please give some feedback to this? I assume this affects GQL only and not NQL, because we use GQL in the model layer to generate the statements. In general, i guess these bugs are tricky to solve, because we would need a lot of more sub queries i assume? (I have not player with the SQL statements yet.)

Dynamic Routing is currently in beta. We will work on this report as soon as possible 👍 Thanks for your help.

**Comment by kirrg001** [comment]
*Little update:*

This mis-behaviour is caused by [GQL](https://github.com/TryGhost/GQL/issues/16). GQL generates the wrong queries.

We will fix that in **[NQL](https://github.com/NexesJS/NQL)** and *not in GQL*. NQL is the "new" GQL, but it's not finished yet. Ghost does not fully use NQL yet.

I've raised an issue in NQL to keep [track of it](https://github.com/NexesJS/NQL/issues/1).

**Comment by kirrg001** [comment]
Similar/Same report: https://github.com/TryGhost/Ghost/issues/9923

**Comment by vladimir-vg** [comment]
Okay, so current workaround: create any tag and attach to all stories.

**Comment by kirrg001** [comment]
This bug was fixed in [Ghost 2.8.0.](https://github.com/TryGhost/Ghost/releases/tag/2.8.0)

**Comment by pascalandy** [comment]
I confirm this it is working.

```
# filters out few tags from Ghost's homepage
routes:
  /:
    controller: channel
    filter: tag:-[business]
# which excludes tag: [business]

collections:
  /:
    permalink: /{slug}/ 
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

**Comment by gnimmelf** [comment]
I guess the team is on top of it, but it's still very confusing for a newcomer, even with plenty technical background. 

I have the following `routes.yaml`, and it only works on positive tag filtering, `/` still includes those tags.
```
collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-[hash-lang-no]'

  /no/:
    permalink: /no/{slug}/
    template: index
    filter: 'tag:hash-lang-no'
```

However, @pascalandy's fix works, applying a channel for `/`:

So, is it fixed, ref @kirrg001 [mentions v2.8.0](https://github.com/TryGhost/Ghost/issues/9950#issuecomment-446545208) above, but latest is 2.26.0 (am I missing s.th?), or the workaround tagging all posts by vladimir-vg, or pascalandy's by using a channel-controller?
