### ISSUE TITLE
Duplicated entries in /sitemap-pages.xml after uploading routes.yaml

### ISSUE THREAD

**Issue by TonnyORG** [TryGhost/Ghost#9956]
### Issue Summary [EDITED]

**NOTE:** After a couple tests, @kirrg001 figured out this only happens when you upload your `routes.yaml` file through the admin. There is a way to fix it, if you restart your ghost server after uploading the routes file.

Using the multi-language feature (dynamic routing), it creates duplicated records on the `/sitemap-pages.xml` file (see image)

![Imgur](https://i.imgur.com/Rb4O7ay.png)

### To Reproduce

Using this `routes.yaml` file:
```
routes:

collections:
  /:
    permalink: /{slug}/
    filter: 'tag:-[en,es]'
    template:
      - index
  /en/:
    permalink: /en/{slug}/
    filter: 'tag:en'
  /es/:
    permalink: /es/{slug}/
    filter: 'tag:es'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

### Technical details:

* Ghost Version: 2.2.0 
* Node Version: v8.12.0
* Browser/OS: Chrome 69.0.3497.100 / MacOS High Sierra
* Database: MySQL
